from medspacy.section_detection import SectionRule

section_rules = [
    SectionRule(category="labs", literal="Lab results:"),
    SectionRule(category="labs", literal="Results:"),
    SectionRule(category="addendum", literal="ADDENDUM:"),
    SectionRule(category="addendum", literal="Addendum:"),
    SectionRule(category="allergies", literal="ALLERGIC REACTIONS:"),
    SectionRule(category="allergies", literal="ALLERGIES:"),
    SectionRule(category="chief_complaint", literal="CC:"),
    SectionRule(category="chief_complaint", literal="CHIEF COMPLAINT:"),
    SectionRule(category="chief_complaint", literal="Chief Complaint:"),
    SectionRule(category="comments", literal="COMMENTS:"),
    SectionRule(category="date", literal="Date:"),
    SectionRule(category="date", literal="Test Date:"),
    SectionRule(category="location", literal="Location:"),
    SectionRule(category="diagnoses", literal="ADMISSION DIAGNOSES:"),
    SectionRule(category="diagnoses", literal="DIAGNOSES:"),
    SectionRule(category="diagnoses", literal="Diagnosis:"),
    SectionRule(category="diagnoses", literal="Primary Diagnosis:"),
    SectionRule(category="diagnoses", literal="Primary:"),
    SectionRule(category="diagnoses", literal="SECONDARY DIAGNOSES:"),
    SectionRule(category="diagnoses", literal="Secondary Diagnoses:"),
    SectionRule(category="diagnoses", literal="Secondary Diagnosis:"),
    SectionRule(category="diagnoses", literal="Secondary:"),
    SectionRule(category="diagnoses", literal="IMPRESSION/CLINICAL DECISION MAKING:"),
    SectionRule(category="labs_and_studies", literal="ADMISSION LABS:"),
    SectionRule(category="labs_and_studies", literal="Admission Labs:"),
    SectionRule(category="labs_and_studies", literal="Discharge Labs:"),
    SectionRule(category="labs_and_studies", literal="ECHO:"),
    SectionRule(category="labs_and_studies", literal="FINDINGS:"),
    SectionRule(category="labs_and_studies", literal="Findings:"),
    SectionRule(category="labs_and_studies", literal="INDICATION:"),
    SectionRule(category="labs_and_studies", literal="LABS:"),
    SectionRule(category="labs_and_studies", literal="Labs:"),
    SectionRule(category="labs_and_studies", literal="MICRO:"),
    SectionRule(category="labs_and_studies", literal="Micro:"),
    SectionRule(category="labs_and_studies", literal="Microbiology:"),
    SectionRule(category="labs_and_studies", literal="Pertinent Results:"),
    SectionRule(category="labs_and_studies", literal="STUDIES:"),
    SectionRule(category="labs_and_studies", literal="Studies:"),
    SectionRule(category="outside_covid_labs", literal="COVID-19 OUTSIDE TEST RESULTS:"),
    SectionRule(category="outside_covid_labs", literal="Entry of Outside Tests/Reports:"),
    SectionRule(category="outside_covid_labs", literal="Documentation of outside COVID-19 information"),
    SectionRule(category="outside_covid_labs", literal="Prior COVID-19 testing:"),
    SectionRule(category="outside_covid_labs", literal="Patient COVID-19 test results:"),
    SectionRule(category="covid_telephone_note", literal="COVID FOLLOW UP TELEPHONE NOTE"),
    SectionRule(category="covid_question", literal="Where was the test performed?", parents=["telephone_note"], parent_required=True),
    SectionRule(category="covid_question", literal="Does the patient have a Positive COVID test result outside the VA?", parents=["telephone_note", "outside_covid_labs"], parent_required=True)
]
